# A short introduction to Python

Before we can accomplish anything in AI or machine learning, we need a programming language to do it. In this notebook, we will go over programming in Python. We will not cover some of the more basic programming conventions, and assume that the student is at least familiar with the concepts of variables, functions, etc.

## What is python?
---
Python is a high-level * interpreted * general-purpose computer language. An interpreted language is a language whose code does not need to be compiled before execution. This is quite different from languages such as C, C ++, and Fortran, where one has to compile human readable code into machine instructions.

In Python, all code is executed by Python's "interpreter", a main program that reads our human-readable code and translates it into machine code when it is executed. This enables a number of dynamic features that are not supported in compiled languages. For example, the Jupyter notebook we use now wouldn't be possible without an interpreted language like Python.

In [79]:
# An example of interpreted code execution ...!
# (Comments are made using the # symbol)
2 + 2

4

Python also allows "dynamic typing": the types of variables are not assigned by the encoder, but are deduced directly by the Python interpreter. This gives the programmer the ability to prototype quickly, but can sometimes require additional code to make sure you have the right type! Let's look at an example of dynamic typing.

In [80]:
## A variable can be of any type.
x = 2     # x is an integer...
x = 2.0   # x is a float...
x = 'hi'  # x isaun string...

## This can cause problems!
x = 2 + x

TypeError: unsupported operand type(s) for +: 'int' and 'str'

As we can see, if we are not careful reassigning variables can cause problems. So we have to be careful not to overuse this feature. We can also see that we got our first mistake! The Python interpreter will report errors as soon as they occur. In a compiled language such as C, the compiler would have returned an error during compilation because it would have detected this type of collision as a compilation error. However, for Python, since we only know the type of variable at runtime, we instead have a runtime error at runtime for this type of type mismatch.
However, by summarizing the typing and addressing of variables, Python avoids many of the runtime errors that often appear in compiled languages. For example, we will not encounter pointer errors, memory leaks, or other runtime errors (segmentation errors) often encountered in C and C ++. Not having to troubleshoot memory issues is a big advantage over type checking. For specific comparisons between Python and other languages, [check out this page](https://www.python.org/doc/essays/comparisons/); in particular:

> *"Python code is typically 3-5 times shorter than equivalent Java code, it is often 5-10 times shorter than equivalent C++ code! Anecdotal evidence suggests that one Python programmer can finish in two months what two C++ programmers can't complete in a year."* -- Python Software Foundation

Let's start our recap on Python coding by going over many structures and variables that we use in programs. How about a "Hello World"?## Python 101
---
Commençons notre recapitulatif sur le codage Python en passant en revue de nombreuses structures et variables  que nous utilisons dans les programmes. Que diriez-vous d'un "Hello World"?

In [81]:
print('Hello World!')

Hello World!


Very simple, right? You can access the documentation for "print"

In [82]:
help(print)

Help on built-in function print in module builtins:

print(*args, sep=' ', end='\n', file=None, flush=False)
    Prints the values to a stream, or to sys.stdout by default.

    sep
      string inserted between values, default a space.
    end
      string appended after the last value, default a newline.
    file
      a file-like object (stream); defaults to the current sys.stdout.
    flush
      whether to forcibly flush the stream.



Print commands can take different types of objects as input, not just strings. The object just needs to have a display option defined.

In [83]:
print(2.0)     # ... float
print(2)       # ... integer
print('c')     # ... string
print(print)   # ..."a function handle"

2.0
2
c
<built-in function print>


Now let's try a little arithmetic. All normal math operations behave as expected.

In [84]:
## Set some variables !
a = 2
b = 3
print('1)', a, '+', b, '=', a+b)
print('2)', a, '-', b, '=', a-b)
print('3)', a, '*', b, '=', a*b)
print('4)', a, '/', b, '=', a/b)
print('5)', a, '^', b, '=', a**b)
print('6)', a, '%', b, '=', a%b)

1) 2 + 3 = 5
2) 2 - 3 = -1
3) 2 * 3 = 6
4) 2 / 3 = 0.6666666666666666
5) 2 ^ 3 = 8
6) 2 % 3 = 2


Now let's look at some control flow structures. Let's first see the format of the connection code, for example: * if-then-else *. These instructions work in Python just as you would expect in any other language you know. However, we have to be careful with the syntax. Unlike languages such as C / C ++, where spaces are very fluid and left to the programmer via backeting, the Python interpreter requires strict code indentation instead of bracketing.

In [85]:
some_value = -1

# Branch based on the sign of the value
if some_value == 0:
    print('Value is equal to 0.')
elif some_value > 0:
    print('Value is positive.')
else:
    print('Value is negative.')

Value is negative.


Note that Python does not include an explicit `switch` control structure like in C / C ++. Instead, we use a ladder of `if-elif-elif -...` instructions to achieve the same goal, as we see above. Since Python 2.5, Python also has a ternary operator ...

In [86]:
some_value = -2

# Ternary operator is given as
#    a if condition else b
print('Value >= 0') if some_value >= 0 else print('Value is negative.')

Value is negative.


Now we'll take a look at basic loops in Python. In practice, the most common loop you will connect with is the `for` loop. Let's take a look at an example.

In [87]:
n_loops = 3

# We need an object to loop over. `range(0,x)` returns an iterator over the range [0,...,x-1]. 
for loop in range(0,n_loops):
    print('Loop #',loop)

Loop # 0
Loop # 1
Loop # 2


In Python, you can loop through an iterable object, not just numeric values. Let's take a look at a simple example creating a list of values.

In [88]:
# Iterate over a list of string values
list_of_strings = ['just', 'a', 'list', 'of', 'strings']

for string in list_of_strings:
    print(string)

just
a
list
of
strings


Interestingly, due to the nature of dynamic typing in Python, our listings aren't limited to just one type. A list can contain any number of objects, each of a different type.

In [89]:
# Iterate over whatever
list_of_whatever = ['just', 42, 'things', 3.14, print, ('i', 'guess')]

for thing in list_of_whatever:
    print(thing)

just
42
things
3.14
<built-in function print>
('i', 'guess')


---

---
## Ex 1: computing n!
For example, let's write a function to calculate the factorial of a given positive integer, $ n! = n \times (n-1) \times (n-2) \times \cdots $, and $ 0! = 1 $. Let's define this as a function so that we can use it again later.

In [90]:
## Your solution below...
from math import floor


def factorial(n):
    if n == 0:
        return 1
    res = 1
    if n % floor(n) != 0 or n < 0:
        print("Error: n must be a non-negative integer.")
        return None
    for i in range(1,n+1):
        res *= i
    return res # Replace with your code

### Validation


In [91]:
assert factorial(0) == 1
assert factorial(6) == 720
assert factorial(5) == 120
assert factorial(10) == 3628800
factorial(-1)
factorial(2.5)
print("Tests Passed !")

Error: n must be a non-negative integer.
Error: n must be a non-negative integer.
Tests Passed !


---

---

## Python knows maths!
Now let's see how to perform a number of basic math operations in python, including examples of linear algebra. First, let's take a look at some simple scalar math operations.

In this case, we'll need to import additional functionality from the `math` package, a standard Python module that comes with the main Python distribution. Import functionality is handled the same as C \ C ++, however, there are some namespace considerations to be aware of.

For example, if we want to use the exponential function of the `math` package, we have several ways to do it, depending on our wishes as programmers.

1. The simple method:

```python
>>> import math
>>> math.exp(1)
2.718281828459045
```

2. Rename the package with a shorter name:

```python
>>> import math as m
>>> m.exp(1)
2.718281828459045
```

3. Import only parts of the package:

```python
>>> from math import exp
>>> exp(1)
2.718281828459045
```

There is no one right way to approach this, you just need to find an approach that meets your needs and makes your code concise and readable.

In [92]:
import math as m   # Just making an easy short name

# Lets look at a basic right triangle...
#      |\
#      | \  h = ?
# a=3  |  \
#      |___\
#       b=1
#

a = 3
b = 1
ang_ab = 90

# Calculate the hypotenuse
h = m.sqrt(a**2 + b**2)

# Find remaining angles
ang_bh = m.degrees(m.asin(a / h))
ang_ah = 180 - ang_ab - ang_bh

# Show results
print('      %0.1f' % ang_ah)
print('       | \\')
print('       |  \\')
print('       |   \\')      
print('a = ',a,'|    \\  h = %0.1f' % h)
print('       |     \\')
print('       |      \\')
print('       |       \\')
print('       |90__%0.1f\\' % ang_bh)  
print('         b =',b)

      18.4
       | \
       |  \
       |   \
a =  3 |    \  h = 3.2
       |     \
       |      \
       |       \
       |90__71.6\
         b = 1


So, we can do simple trigonometry. But we can also do logarithms, exponentials, etc. We also have some specific constants which are defined for us in `math`.

In [93]:
m.log(m.exp(m.pi))   # m.log() defaults to natural log

3.141592653589793

## List, dictionaires, sets & tuples

Python includes several types of built-in containers: lists, dictionaries, sets, and t-uples.

**list**: A list is the Python equivalent of an array, but is resizable and can contain elements of different types:

In [94]:
xs = [3, 1, 2]    # Create a list
print(xs, xs[2])  # Prints "[3, 1, 2] 2"
print(xs[-1])     # Negative indices count from the end of the list; prints "2"
xs[2] = 'foo'     # Lists can contain elements of different types
print(xs)         # Prints "[3, 1, 'foo']"
xs.append('bar')  # Add a new element to the end of the list
print(xs)         # Prints "[3, 1, 'foo', 'bar']"
x = xs.pop()      # Remove and return the last element of the list
print(x, xs)      # Prints "bar [3, 1, 'foo']"

[3, 1, 2] 2
2
[3, 1, 'foo']
[3, 1, 'foo', 'bar']
bar [3, 1, 'foo']


**Slicing**: In addition to accessing the elements of a list at a time, Python provides a concise syntax for accessing sublists. this is called slicing:

In [95]:
nums = list(range(5))     # range is a built-in function that creates a list of integers
print(nums)               # Prints "[0, 1, 2, 3, 4]"
print(nums[2:4])          # Get a slice from index 2 to 4 (exclusive); prints "[2, 3]"
print(nums[2:])           # Get a slice from index 2 to the end; prints "[2, 3, 4]"
print(nums[:2])           # Get a slice from the start to index 2 (exclusive); prints "[0, 1]"
print(nums[:])            # Get a slice of the whole list; prints "[0, 1, 2, 3, 4]"
print(nums[:-1])          # Slice indices can be negative; prints "[0, 1, 2, 3]"
nums[2:4] = [8, 9]        # Assign a new sublist to a slice
print(nums)               # Prints "[0, 1, 8, 9, 4]"

[0, 1, 2, 3, 4]
[2, 3]
[2, 3, 4]
[0, 1]
[0, 1, 2, 3, 4]
[0, 1, 2, 3]
[0, 1, 8, 9, 4]


**dictionaries:** A dictionary stores pairs (key, value): You can use it like this:

In [96]:
d = {'cat': 'cute', 'dog': 'furry'}  # Create a new dictionary with some data
print(d['cat'])       # Get an entry from a dictionary; prints "cute"
print('cat' in d)     # Check if a dictionary has a given key; prints "True"
d['fish'] = 'wet'     # Set an entry in a dictionary
print(d['fish'])      # Prints "wet"
# print(d['monkey'])  # KeyError: 'monkey' not a key of d
print(d.get('monkey', 'N/A'))  # Get an element with a default; prints "N/A"
print(d.get('fish', 'N/A'))    # Get an element with a default; prints "wet"
del d['fish']         # Remove an element from a dictionary
print(d.get('fish', 'N/A')) # "fish" is no longer a key; prints "N/A"

d = {'person': 2, 'cat': 4, 'spider': 8}
for animal in d:
    legs = d[animal]
    print('A %s has %d legs' % (animal, legs))
# Prints "A person has 2 legs", "A cat has 4 legs", "A spider has 8 legs"

cute
True
wet
N/A
wet
N/A
A person has 2 legs
A cat has 4 legs
A spider has 8 legs


**set**: A set is an unordered collection of distinct elements. As a simple example, consider the following:

In [97]:
animals = {'cat', 'dog'}
print('cat' in animals)   # Check if an element is in a set; prints "True"
print('fish' in animals)  # prints "False"
animals.add('fish')       # Add an element to a set
print('fish' in animals)  # Prints "True"
print(len(animals))       # Number of elements in a set; prints "3"
animals.add('cat')        # Adding an element that is already in the set does nothing
print(len(animals))       # Prints "3"
animals.remove('cat')     # Remove an element from a set
print(len(animals))       # Prints "2"

animals = {'cat', 'dog', 'fish'}
for idx, animal in enumerate(animals):
    print('#%d: %s' % (idx + 1, animal))
# Prints "#1: fish", "#2: dog", "#3: cat"

True
False
True
3
3
2
#1: fish
#2: dog
#3: cat


**tuple**: A t-tuple is an ordered (immutable) list of values. A tuple is in many ways similar to a list; One of the most important differences is that tuples can be used as keys in dictionaries and as elements of sets, while lists cannot. Here is a trivial example:

In [98]:
d = {(x, x + 1): x for x in range(10)}  # Create a dictionary with tuple keys
t = (5, 6)        # Create a tuple
print(type(t))    # Prints "<class 'tuple'>"
print(d[t])       # Prints "5"
print(d[(1, 2)])  # Prints "1"

<class 'tuple'>
5
1


## Statistics in Python

Now let's say you want to do some statistics. Maybe you want to start pulling samples from a particular distribution ... or maybe you want to check its entropy? As with everything that happens in Python, you have to assume that this has already been implemented, and look for a package ... in particular, for anything statistical, here is scipy.stats: [(Full documentation here)](https://docs.scipy.org/doc/scipy-0.18.1/reference/stats.html).

In [99]:
import scipy.stats as stat

# Calculate the entropy of a Laplace distribution
mu  = 1
sig = 3
e = stat.laplace.entropy(loc=mu,scale=sig)    # Differential Entropy...

# What about the higher-order moments?
m, v, s, k = stat.laplace.stats(loc=mu,scale=sig,moments='mvsk')

print('---- true dist. stats----')
print('Mean           = %0.3f' % m)
print('Variance       = %0.3f' % v)
print('Skew           = %0.3f' % s)
print('Kurtosis       = %0.3f' % k)
print('Diff. Entropy  = %0.3f' % e)

# We can generate data from this distribution
data = stat.laplace.rvs(loc=mu, scale=sig, size=1000)

# Fit parameters
mu_fit, sig_fit = stat.laplace.fit(data)

# See values
m, v, s, k = stat.laplace.stats(loc=mu_fit,scale=sig_fit,moments='mvsk')
e = stat.laplace.entropy(loc=mu_fit,scale=sig_fit)

print('---- est dist. stats----')
print('Mean           = %0.3f' % m)
print('Variance       = %0.3f' % v)
print('Skew           = %0.3f' % s)
print('Kurtosis       = %0.3f' % k)
print('Diff. Entropy  = %0.3f' % e)

---- true dist. stats----
Mean           = 1.000
Variance       = 18.000
Skew           = 0.000
Kurtosis       = 3.000
Diff. Entropy  = 2.792
---- est dist. stats----
Mean           = 1.208
Variance       = 18.221
Skew           = 0.000
Kurtosis       = 3.000
Diff. Entropy  = 2.798


## Linear algebra in Python: numpy

Linear algebra and array manipulation will be fundamental in this course. For this, lists, dictionaries, etc ... are not really suitable, because they do not allow us to treat arrays as matrices; and we will need to use one of the most important tools in the python galaxy: the numpy arrays!

In [100]:
# Make use of numpy
import numpy as np

a = np.array([1, 2, 3])   # Create a rank 1 array
print(type(a))            # Prints "<class 'numpy.ndarray'>"
print(a.shape)            # Prints "(3,)"
print(a[0], a[1], a[2])   # Prints "1 2 3"
a[0] = 5                  # Change an element of the array
print(a)                  # Prints "[5, 2, 3]"

b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
print(b.shape)                     # Prints "(2, 3)"
print(b[0, 0], b[0, 1], b[1, 0])   # Prints "1 2 4"

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
1 2 4


Numpy allows us to create tables of all kinds:

In [101]:
a = np.zeros((2,2))   # Create an array of all zeros
print(a)              # Prints "[[ 0.  0.]
                      #          [ 0.  0.]]"

b = np.ones((1,2))    # Create an array of all ones
print(b)              # Prints "[[ 1.  1.]]"

c = np.full((2,2), 7)  # Create a constant array
print(c)               # Prints "[[ 7.  7.]
                       #          [ 7.  7.]]"

d = np.eye(2)         # Create a 2x2 identity matrix
print(d)              # Prints "[[ 1.  0.]
                      #          [ 0.  1.]]"

e = np.random.random((2,2))  # Create an array filled with random values
print(e)                     # Might print "[[ 0.91940167  0.08143941]
                             #               [ 0.68744134  0.87236687]]"

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.0194214  0.36664178]
 [0.84947732 0.93148388]]


Numpy offers several methods for indexing in arrays.

Slicing: Similar to Python lists, numpy arrays can be sliced. Since arrays can be multidimensional, you must specify a slice for each dimension in the array.

In [102]:
# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]

# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
print(a[0, 1])   # Prints "2"
b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])   # Prints "77"

2
77


You can also combine integer indexing with slice indexing. However, this will produce an array of lower rank than the original one. Note that this is quite different from the way MATLAB handles matrix slicing:

In [103]:
# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Two ways of accessing the data in the middle row of the array.
# Mixing integer indexing with slices yields an array of lower rank,
# while using only slices yields an array of the same rank as the
# original array:
row_r1 = a[1, :]    # Rank 1 view of the second row of a
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
print(row_r1, row_r1.shape)  # Prints "[5 6 7 8] (4,)"
print(row_r2, row_r2.shape)  # Prints "[[5 6 7 8]] (1, 4)"

# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)  # Prints "[ 2  6 10] (3,)"
print(col_r2, col_r2.shape)  # Prints "[[ 2]
                             #          [ 6]
                             #          [10]] (3, 1)"

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


### Maths and arrays
Basic math functions work on an array-by-array basis on arrays and are available both as an operator overload and as functions in the numpy module:

In [104]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
# [[ 6.0  8.0]
#  [10.0 12.0]]
print(x + y)
print(np.add(x, y))

# Elementwise difference; both produce the array
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print(x - y)
print(np.subtract(x, y))

# Elementwise product; both produce the array
# [[ 5.0 12.0]
#  [21.0 32.0]]
print(x * y)
print(np.multiply(x, y))

# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


Note that unlike MATLAB, * is element multiplication, not matrix multiplication. Instead, we use the dot function to calculate the internal products of vectors, to multiply a vector by a matrix, and to multiply matrices. dot is available both as a function in the numpy module and as an instance method of array objects.

In [105]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))

# Matrix / vector product; both produce the rank 1 array [29 67]
print(x.dot(v))
print(np.dot(x, v))

# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))

219
219
[29 67]
[29 67]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


You can also use @ as a matrix multiplication symbol, which keeps the notation pleasant.

In [106]:
# Inner product of vectors; both produce 219
print(v@w)

# Matrix / vector product; both produce the rank 1 array [29 67]
print(x@v)

# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print(x@y)

219
[29 67]
[[19 22]
 [43 50]]


### Numpy Broadcasting

Numpy Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations. We frequently have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operations on the larger array.
For example, suppose we want to add a constant vector to each row of a matrix. We could do it like this:

In [107]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # Create an empty matrix with the same shape as x

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v

# Now y is the following
# [[ 2  2  4]
#  [ 5  5  7]
#  [ 8  8 10]
#  [11 11 13]]
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


It works; However, when the matrix x is very large, computing an explicit loop in Python can be slow. Note that adding the vector v to each row of the matrix x is like forming a matrix vv by stacking multiple copies of v vertically, then performing the elementary sum of x and vv. We could implement this approach like this:

In [108]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
vv = np.tile(v, (4, 1))   # Stack 4 copies of v on top of each other
print(vv)                 # Prints "[[1 0 1]
                          #          [1 0 1]
                          #          [1 0 1]
                          #          [1 0 1]]"
y = x + vv  # Add x and vv elementwise
print(y)  # Prints "[[ 2  2  4
          #          [ 5  5  7]
          #          [ 8  8 10]
          #          [11 11 13]]"

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


Numpy delivery allows us to perform this calculation without actually creating multiple copies of v. Consider this version, using broascasting:

In [109]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting
print(y)  # Prints "[[ 2  2  4]
          #          [ 5  5  7]
          #          [ 8  8 10]
          #          [11 11 13]]"

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [110]:
import numpy as np

# Compute outer product of vectors
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)
# To compute an outer product, we first reshape v to be a column
# vector of shape (3, 1); we can then broadcast it against w to yield
# an output of shape (3, 2), which is the outer product of v and w:
# [[ 4  5]
#  [ 8 10]
#  [12 15]]
print(np.reshape(v, (3, 1)) * w)

# Add a vector to each row of a matrix
x = np.array([[1,2,3], [4,5,6]])
# x has shape (2, 3) and v has shape (3,) so they broadcast to (2, 3),
# giving the following matrix:
# [[2 4 6]
#  [5 7 9]]
print(x + v)

# Add a vector to each column of a matrix
# x has shape (2, 3) and w has shape (2,).
# If we transpose x then it has shape (3, 2) and can be broadcast
# against w to yield a result of shape (3, 2); transposing this result
# yields the final result of shape (2, 3) which is the matrix x with
# the vector w added to each column. Gives the following matrix:
# [[ 5  6  7]
#  [ 9 10 11]]
print((x.T + w).T)
# Another solution is to reshape w to be a column vector of shape (2, 1);
# we can then broadcast it directly against x to produce the same
# output.
print(x + np.reshape(w, (2, 1)))

# Multiply a matrix by a constant:
# x has shape (2, 3). Numpy treats scalars as arrays of shape ();
# these can be broadcast together to shape (2, 3), producing the
# following array:
# [[ 2  4  6]
#  [ 8 10 12]]
print(x * 2)

[[ 4  5]
 [ 8 10]
 [12 15]]
[[2 4 6]
 [5 7 9]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 2  4  6]
 [ 8 10 12]]


## Classes
---
Like C / C ++ and Java, Python supports class structures. However, it is not an "object oriented language" in the truest sense. It does not support strict encapsulation, that is, the privatization of object data. However, it supports the convenience of classes in a whole other way. Let's take a look at an example. Here we define a class for an * Agent *, which moves on a 2D grid, evaluating the utility surrounding it.

In [111]:
class Agent:
    """
        A simple class which defines an `agent`, some decision making
        entity which wants to maximize its own reward.
    """    
    def __init__(self, utility=0, position=(0.0,0.0), utility_func = None, step_size = 1.0):
        """
            The initialization function gets called by the interpreter
            every time a new object of the Agent class gets created.
            
            :param utility: Agent's current utility value.
            :param utility_func: Function with which to evaluate the utility of the agent. 
                                 The funciton `utility_func` takes an (x,y) coordinate and
                                 reports a utility.
            :param position: Agent's current position (x,y)
            
        """
        self.utility = utility
        self.position = position
        self.utility_func = utility_func
        self.history = dict(position = [], utility = [])
        self.step_size = step_size
    
    def __repr__(self):
        """
            This function gets called whenever the interpreter needs a "formal" 
            string representation (error logs, etc.)
        """
        return "Agent<p:%s, u:%s>" %(self.position, self.utility)
    
    def __str__(self):
        """
            This function gets called by the interpreter whenever
            there needs to be a "user friendly" 
            string description of the Agent object (e.g. `print(Agent())`).
        """
        return "Agent @ %s [u=%s]" % (self.position, self.utility)
    
    def record_state(self):
        """
            Store the current state of the agent in a queue.
        """
        self.history['position'].append(self.position)
        self.history['utility'].append(self.utility)
    
    def move_up(self):
        """
            Increment the Y coordinate of the agent.
        """
        self.record_state()
        self.position = (self.position[0], self.position[1]+self.step_size)
        self.utility = self.evaluate_utility()
        
    def move_down(self):
        """
            Decrement the Y coordinate of the agent.
        """
        self.record_state()
        self.position = (self.position[0], self.position[1]-self.step_size)
        self.utility = self.evaluate_utility()
        
    def move_left(self):
        """
            Decrement the X coordinate of the agent
        """
        self.record_state()
        self.position = (self.position[0]-self.step_size, self.position[1])
        self.utility = self.evaluate_utility()
        
    def move_right(self):
        """
            Increment the X coordinate of the agent
        """
        self.record_state()
        self.position = (self.position[0]+self.step_size, self.position[1])
        self.utility = self.evaluate_utility()
        
    def evaluate_utility(self, offset=(0.0, 0.0)):
        """
            Get the utility function relative to the current agent
            location. Optinally, evaluate at some offset from the agent.
            
            :param offset: Tuple of (x,y) coordinates with which to offset the agent
                           position to evaluate the utility.
            :return: A numeric value for the utility at the evaluated point
        """
        if self.utility_func == None:
            return 0   # Simple Agent with simple utility
        else:
            return self.utility_func((self.position[0]+offset[0],
                                      self.position[1]+offset[1]))
        


To use the class, all you have to do is initialize an object with the agent's constructor. In this case, all default values are used. Additionally, we do not yet specify a utility function for the space in which the agent resides. We can call functions of the agent class for that particular agent and see what it is.

In [112]:
# Instantiate the Agent object, `henri`...
henri = Agent()
print('[t = 0]', henri, 'History:', henri.history)

# Try moving around a bit and look at the history
henri.move_up()
print('[t = 1]', henri, 'History:', henri.history)

henri.move_left()
print('[t = 2]', henri, 'History:', henri.history)

henri.move_up()
print('[t = 3]', henri, 'History:', henri.history)

[t = 0] Agent @ (0.0, 0.0) [u=0] History: {'position': [], 'utility': []}
[t = 1] Agent @ (0.0, 1.0) [u=0] History: {'position': [(0.0, 0.0)], 'utility': [0]}
[t = 2] Agent @ (-1.0, 1.0) [u=0] History: {'position': [(0.0, 0.0), (0.0, 1.0)], 'utility': [0, 0]}
[t = 3] Agent @ (-1.0, 2.0) [u=0] History: {'position': [(0.0, 0.0), (0.0, 1.0), (-1.0, 1.0)], 'utility': [0, 0, 0]}


With the way we wrote the `Agent` class, we can also pass any position-based utility function to it. Let's think about putting Henri in a sort of landscape. In this case, what about a simple isometric 2D Gaussian utility that has a single maximization point, so something that follows a simple function like ...
$$U(\mathbf{x}) = \frac{1}{2\pi\sigma} e ^{-\frac{(\mathbf{x} - \boldsymbol{\mu})^T(\mathbf{x} - \boldsymbol{\mu})}{2\sigma^2} }$$

In [113]:
from math import exp, sqrt, pi

def gaussian_utility(position, mean=(0.0,0.0), sig=1.0):
    """
        A simple utility function, essentially just an iid 
        multivariate normal.
    """
    # Get the variance
    v = sig**2
    # Calculate distance from mean
    d = (position[0] - mean[0], position[1] - mean[1])
    dTd = d[0]**2/v + d[1]**2/v
    # Scaling
    scale = 1/(2*pi*v)
    # Final computation
    utility = scale * exp(-0.5 * dTd)
    utility += 1e-12
        
    return utility

Now that we've defined a utility function, let's put Henri "in the field", so to speak. We can assign this utility function to our `Agent` class by means of a **lambda** function.

A lambda function allows us to define a new call to a specific function in which some parameters are fixed and some are variable. In our case, we want the parameters of the utility function (the mean and standard deviation) to remain fixed, while changing the position. A simple lambda function definition looks like the following example.

```python
    >>> def foo(param1, param2):
    ...     return param1 + param2
    ...
    >>> foo_single_param = lambda value: foo(value, 4)
    >>> foo_single_param(2)
    6
```

We can use it to pass a lambda function as an agent utility. Let's see how to do this, below

In [114]:
# Define some parameters for the utility function
utility_peak = (2.0,2.0)
utility_sigma = 1.0

utility_lambda = lambda position: gaussian_utility(position, mean=utility_peak, sig=utility_sigma)

henri = Agent(utility_func = utility_lambda)
print('[t = 0]', henri)

# Try moving around a bit and look at the history
henri.move_up()
print('[t = 1]', henri)

henri.move_right()
print('[t = 2]', henri)

henri.move_up()
print('[t = 3]', henri)

henri.move_right()
print('[t = 4]', henri)

henri.move_up()
print('[t = 5]', henri)

[t = 0] Agent @ (0.0, 0.0) [u=0]
[t = 1] Agent @ (0.0, 1.0) [u=0.013064233285684922]
[t = 2] Agent @ (1.0, 1.0) [u=0.05854983152531917]
[t = 3] Agent @ (1.0, 2.0) [u=0.09653235263105392]
[t = 4] Agent @ (2.0, 2.0) [u=0.15915494309289535]
[t = 5] Agent @ (2.0, 3.0) [u=0.09653235263105392]


---

---

## Ex. 2 Stochastic Climber
Let's say we have a climber and he wants to climb the highest peak. However, a heavy fog has descended on the valley in which he resides. He can only see the ground right in front of him. He knows that if he always goes up the path every step of the way, he will get to a top ... but probably not to the highest peak. Instead, he plans to take an alternative stochastic strategy.

At each time interval, it looks at the paths in front of it: N, S, E and W. It then takes off in a random direction, the probability of which is proportional to the slopes that surround it. He thinks it will at least give him a chance to get to the highest peak.

Write a class that inherits from the `Agent` class and extends it into a `StochasticClimber` class. Write a `climb` function which takes the number of time steps as input and runs the stochastic climber.

In [115]:
import random

class StochasticClimber(Agent):    # Inherit from class Agent
    def climb(self, steps=1):
        """ Implement me !
            Run the stochastic climber for the specified number of steps
        """
        for step in range(0,steps):
            utility_n = self.evaluate_utility(offset=(0.0, self.step_size))
            utility_e = self.evaluate_utility(offset=(self.step_size, 0.0))
            utility_s = self.evaluate_utility(offset=(0.0, -self.step_size))
            utility_w = self.evaluate_utility(offset=(-self.step_size, 0.0))
        
            direction = random.choices(['n', 's', 'e', 'w'],  weights=[utility_n, utility_s, utility_e, utility_w])[0]

            if direction == 'n':
                self.move_up()
            elif direction == 's':
                self.move_down()
            elif direction == 'e':
                self.move_right()
            elif direction == 'w':
                self.move_left()
            
        pass

*Solution*

In [116]:
# %load example2.py

### Validation

In [117]:
# Create some landscape for our climber. In this case we have a mountain range like the following
#          L
#          |
#          G
#        /  \
#       L    L
#
#    S   <-- start position
#
mountain_range = lambda p : gaussian_utility(p, mean=(2.0,2.0), sig = 0.1) + \
                            gaussian_utility(p, mean=(2.0,3.0), sig = 0.5) + \
                            gaussian_utility(p, mean=(1.0,1.0), sig = 0.5) + \
                            gaussian_utility(p, mean=(3.0,1.0), sig = 0.5)
            

# Run our climber
yves = StochasticClimber(utility_func=mountain_range, step_size=0.05)
yves.climb(steps=40000)

---

---

## File I/O

Now that we have run our experiment with the `StochasticClimber`, lets say that we want to save that data to disk for use later. Perhaps for a figure (e.g. next notebook). It would be nice to not have to re-run the experiment each time we want to generate a new figure ! Lets take a look at basic file I/O and see how to write a Python or CSV file containing our results. 

In the first case, lets take a look at the simplest approach, which is to store the entire `yves` object to disk. Using the `pickle` module, we can store Python data to disk and load it again later. This works in much the same was as `mat` files in Matlab. 

In [118]:
import pickle

# A simple example...
pickle.dump(yves, open('yves.p','wb'))

PicklingError: Can't pickle <function <lambda> at 0x00000273091E0360>: attribute lookup <lambda> on __main__ failed

However, we see that not all things can be pickled. In this case, our lambda function cannot be stored in disk. We will, instead, have to store our static structures (in this case, the history). 

In [119]:
with open('yves.p', 'wb') as pickle_file:
    pickle.dump(yves.history,pickle_file)

This "*`with a as f:`*" control block will attempt to open the specified file and will additionally close the file handle at the end of the block. This is handy in the even that there is an error during the file I/O that might leave a file hanging open.

Now lets take a look at what we've got. As we can see below, we now have the `yves.p` file saved to disk. This contains the `StochasticClimber` history.

In [120]:
%ls

 Volume in drive C is OS
 Volume Serial Number is 78C8-8D32

 Directory of c:\Users\loria\Desktop\EPFL\EPFL_MA3\FOIL\FundamentalLearningEPFL\TP0

15/09/2026  12:00    <DIR>          .
15/09/2026  11:38    <DIR>          ..
15/09/2026  11:38             1'621 example1.py
15/09/2026  11:38             1'093 example2.py
15/09/2026  12:00            61'149 Intro to Python.ipynb
15/09/2026  11:38            27'306 linear-algebra-python-basics.ipynb
15/09/2026  11:38            27'515 my_first_plot.pdf
15/09/2026  11:38            10'960 sine_cosine.pdf
15/09/2026  11:38            13'235 Visualization.ipynb
15/09/2026  12:01         1'160'347 yves.p
               8 File(s)      1'303'226 bytes
               2 Dir(s)  78'246'477'824 bytes free


Now, lets take a look at loading that to make sure that its there.

In [121]:
with open('yves.p','rb') as pickle_file:
    yves_history_copy = pickle.load(pickle_file)
print(yves_history_copy)  # <-- Write a huge dataset below !

{'position': [(0.0, 0.0), (0.0, -0.05), (0.0, 0.0), (0.05, 0.0), (0.1, 0.0), (0.05, 0.0), (0.1, 0.0), (0.15000000000000002, 0.0), (0.15000000000000002, 0.05), (0.2, 0.05), (0.2, 0.1), (0.2, 0.15000000000000002), (0.15000000000000002, 0.15000000000000002), (0.15000000000000002, 0.2), (0.15000000000000002, 0.15000000000000002), (0.10000000000000002, 0.15000000000000002), (0.05000000000000002, 0.15000000000000002), (0.10000000000000002, 0.15000000000000002), (0.05000000000000002, 0.15000000000000002), (0.05000000000000002, 0.2), (1.3877787807814457e-17, 0.2), (0.05000000000000002, 0.2), (1.3877787807814457e-17, 0.2), (0.05000000000000002, 0.2), (0.10000000000000002, 0.2), (0.05000000000000002, 0.2), (0.05000000000000002, 0.15000000000000002), (0.05000000000000002, 0.2), (1.3877787807814457e-17, 0.2), (1.3877787807814457e-17, 0.15000000000000002), (1.3877787807814457e-17, 0.2), (1.3877787807814457e-17, 0.25), (1.3877787807814457e-17, 0.3), (0.05000000000000002, 0.3), (1.3877787807814457e-1

We take note of a few aspects of this pickle example. Specifically, the `pick.dump()` and `pickle.load()` commands take file handles, not file names themselves. This means that we need to specify the read and write options. In both cases we are dumping all the data as binary (not strings), so we specify the 'b' option when using `open()`. 

Now, what do we do if we want to write data to disk that can be accessed by any other program (e.g. Excel, gnuplot, etc...)? We can also write all of this data out as a CSV, too. Lets take a look at this example. Here, we will make use of pandas to do this easily.

In [122]:
import pandas as pd

# Create a new dictionary whose keys represent the headers (columns)
# of information that we would like to store in the CSV file.
yves_csv = dict(x=[], y=[], z=[])
yves_csv['x'] = [yves.history['position'][i][0] for i in range(0,len(yves.history['position']))]
yves_csv['y'] = [yves.history['position'][i][1] for i in range(0,len(yves.history['position']))]
yves_csv['z'] = yves.history['utility']

# Create a DataFrame object from a dictionary
df = pd.DataFrame.from_dict(yves_csv)
# Write to CSV format
df.to_csv("yves.csv", sep=',', header=True, index=False)  
%ls

 Volume in drive C is OS
 Volume Serial Number is 78C8-8D32

 Directory of c:\Users\loria\Desktop\EPFL\EPFL_MA3\FOIL\FundamentalLearningEPFL\TP0

15/09/2026  12:01    <DIR>          .
15/09/2026  11:38    <DIR>          ..
15/09/2026  11:38             1'621 example1.py
15/09/2026  11:38             1'093 example2.py
15/09/2026  12:00            61'149 Intro to Python.ipynb
15/09/2026  11:38            27'306 linear-algebra-python-basics.ipynb
15/09/2026  11:38            27'515 my_first_plot.pdf
15/09/2026  11:38            10'960 sine_cosine.pdf
15/09/2026  11:38            13'235 Visualization.ipynb
15/09/2026  12:01         2'208'442 yves.csv
15/09/2026  12:01         1'160'347 yves.p
               9 File(s)      3'511'668 bytes
               2 Dir(s)  78'059'761'664 bytes free


And now we see the CSV file written out to disk. Voilà! 